# General Parameters
model: 'PixelCNN'
dataset: 'mnist'
n_bits: 1
use_cuda: True
save_model_path: null  # If null, the model is not saved

# Training Parameters
n_blocks: 8
batch_size: 128
num_iters: 5000
lr: 1e-3
eval_every: 500
generate_every: 1000
eval_num_gen: 8
clip_grad: null
final_num_gen: 100

# Logging parameters
experiment_name: 'PixelCNN, binary shapes 1'

############  Neptune Parameters ############
log_neptune: False
neptune_proj_name: 'kareem-elsawah/AR_models'
neptune_tags: ['PixelCNN','mnist']

############  Tensorboard Parameters ############
log_tensorboard: True

############  tqdm and manual logging Parameters ############
log_tqdm: True
log_file: True