# General Parameters
model: 'PixelCNN'
dataset: 'shapes'
n_bits: 1
use_cuda: True
save_model_path: null  # If null, the model is not saved

# Training Parameters
n_blocks: 8
batch_size: 32
num_iters: 1000
lr: 1e-3
eval_every: 500
generate_every: 500
eval_num_gen: 32
clip_grad: null
final_num_gen: 100

# Logging parameters
experiment_name: 'PixelCNN, binary shapes'

############  Neptune Parameters ############
log_neptune: True
neptune_proj_name: 'kareem-elsawah/flow-models'
neptune_tags: ['PixelCNN','shapes','autoregressive']

############  Tensorboard Parameters ############
log_tensorboard: True

############  tqdm and manual logging Parameters ############
log_tqdm: True
log_file: True