# General Parameters
model: 'NCSN'
dataset: 'shapes'
n_bits: 1
use_cuda: True
save_model_path: null  # If null, the model is not saved

# Model Parameters
sigma_1: 1
L: 5

# Training Parameters
batch_size: 16
num_iters: 1000
lr: 5e-4
eval_every: 500
generate_every: 50
eval_num_gen: 32
clip_grad: 5
final_num_gen: 100
floor_gen: False

# Logging parameters
experiment_name: 'NCSN, binary shapes'

############  Neptune Parameters ############
log_neptune: True
neptune_proj_name: 'kareem-elsawah/flow-models'
neptune_tags: ['NCSN','shapes']

############  Tensorboard Parameters ############
log_tensorboard: True

############  tqdm and manual logging Parameters ############
log_tqdm: True
log_file: False