# General Parameters
model: 'Glow'
dataset: 'colored_shapes'
n_bits: 2
use_cuda: True
save_model_path: null  # If null, the model is not saved

# Model Parameters
n_blocks: 1
flows_per_block: 30
large_model: False

# Training Parameters
batch_size: 16
num_iters: 2000
lr: 5e-4
eval_every: 500
generate_every: 500
eval_num_gen: 8
clip_grad: 5
final_num_gen: 100
floor_gen: False

# Logging parameters
experiment_name: 'Glow, binary shapes 1'

############  Neptune Parameters ############
log_neptune: True
neptune_proj_name: 'kareem-elsawah/flow-models'
neptune_tags: ['Glow','shapes']

############  Tensorboard Parameters ############
log_tensorboard: True

############  tqdm and manual logging Parameters ############
log_tqdm: True
log_file: False