# General Parameters
model: 'Glow'
dataset: 'mnist'
n_bits: 1
use_cuda: True
save_model_path: null  # If null, the model is not saved

# Model Parameters
n_blocks: 2
flows_per_block: 30
max_val: 1
large_model: False

# Training Parameters
batch_size: 16
num_iters: 1000
lr: 5e-4
eval_every: 500
generate_every: 250
eval_num_gen: 8
clip_grad: 5
final_num_gen: 100
floor_gen: False

# Logging parameters
experiment_name: 'Glow, binary mnist 1'

############  Neptune Parameters ############
log_neptune: True
neptune_proj_name: 'kareem-elsawah/flow-models'
neptune_tags: ['Glow','mnist']

############  Tensorboard Parameters ############
log_tensorboard: True

############  tqdm and manual logging Parameters ############
log_tqdm: True
log_file: False