# General Parameters
model: 'MADE'
dataset: 'mnist'
n_bits: 1
use_cuda: True
save_model_path: null  # If null, the model is not saved

# Training Parameters
batch_size: 32
num_iters: 10000
lr: 5e-4
eval_every: 500
generate_every: 1000
eval_num_gen: 8
clip_grad: null
final_num_gen: 100

# Logging parameters
experiment_name: 'MADE, binary mnist 1'

############  Neptune Parameters ############
log_neptune: False
neptune_proj_name: 'kareem-elsawah/AR_models'
neptune_tags: ['MADE','mnist']

############  Tensorboard Parameters ############
log_tensorboard: True

############  tqdm and manual logging Parameters ############
log_tqdm: True
log_file: True